#!/bin/bash

CONFIG=c64xAccurate.ccxml
source common.inc.sh

trap 'echo Control-C trap caught; exit 1' 2 #traps Ctrl-C (signal 2)

verbose=0
if [ "$1" = "-v" ]; then
  verbose=1
fi

initlog

for f in `ls Reference/*.reference | sort`; do
  fn=`basename $f`
  outfile=Output/${fn%%.reference}.out
  if [ -e "$outfile" ]; then
	expected=`awk 'BEGIN{ RS="retval = ";} { gsub(/[^0-9].*/,"",$1); if ($1 != ""){ print $1; } }' $f`
    if [ -z $expected ]; then
		expected='UNDEFINED'
	fi
	runtest $outfile $expected
  else
    echo "not found: $outfile"
  fi
done
