#!/bin/bash
CONFIG=c64xAccurate.ccxml

trap 'echo Control-C trap caught; exit 1' 2 #traps Ctrl-C (signal 2)

for outfile in `echo $* | sed 's/ /\n/g' | sort`; do
  fn=`basename $outfile`
  reference=Reference/${fn%%.out}.reference
  if [ -e "$outfile" ]; then
	expected=`awk 'BEGIN{ RS="retval = ";} { gsub(/[^0-9].*/,"",$1); if ($1 != ""){ print $1; } }' $reference`
    if [ -z $expected ]; then
		expected='UNDEFINED'
	fi
    ./retcatch.sh -c $CONFIG $outfile &> .out
	rc=`awk 'BEGIN{ RS="retval = ";} { gsub(/[^0-9].*/,"",$1); if ($1 != ""){ print $1; } }' .out`
    if [ $rc = $expected ]; then
      echo -e " OK     $outfile"
    else
      echo
      echo -e " FAIL   $outfile"
      echo    "        - expected: ($expected)"
      echo    "        - returned: ($rc)"
      echo
    fi
    rm -f .out
  else
    echo "not found: $outfile"
  fi
done
