#!/bin/bash

CONFIG=c64xAccurate.ccxml
source common.inc.sh


trap 'echo Control-C trap caught; exit 1' 2 #traps Ctrl-C (signal 2)

initlog

for outfile in `echo $* | sed 's/ /\n/g' | sort`; do
  fn=`basename $outfile`
  reference=Reference/${fn%%.out}.reference
  if [ -e "$outfile" ]; then
	expected=`awk 'BEGIN{ RS="retval = ";} { gsub(/[^0-9].*/,"",$1); if ($1 != ""){ print $1; } }' $reference`
    if [ -z $expected ]; then
		expected='UNDEFINED'
	fi
	runtest $outfile $expected
  else
    echo "not found: $outfile"
  fi
done
